export type Language = 'zh' | 'en' | 'de'

const zh = {
  dashboard: '总览',
  welcome: '楼宇管理系统',
  systemStatus: '系统状态',
  totalAlarms: '总报警数',
  energyConsumption: '能耗',
  activeUsers: '在线用户',
  systemUptime: '系统运行时间',
  nav: {
    dashboard: '总览', dataAcquisition: '数据采集', heating: '供暖控制', ventilation: '通风控制',
    cooling: '空调调节', lighting: '照明控制', shading: '遮阳控制', schedules: '时间程序',
    alarms: '报警管理', energy: '能耗监测', rooms: '房间自动化', trends: '趋势分析',
    interfaces: '接口管理', users: '用户管理', remote: '远程维护', settings: '系统设置',
  },
  status: { normal: '正常', warning: '警告', alarm: '报警', offline: '离线', online: '在线', maintenance: '维护' },
  actions: { refresh: '刷新', export: '导出', settings: '设置', save: '保存', cancel: '取消', add: '添加', edit: '编辑', delete: '删除', confirm: '确认', search: '搜索', reset: '重置', close: '关闭', start: '启动', stop: '停止', connect: '连接', disconnect: '断开', backup: '备份', update: '更新', acknowledge: '确认报警', silence: '静默' },
  common: { time: '时间', type: '类型', name: '名称', status: '状态', operation: '操作', module: '模块', content: '内容', level: '级别', device: '设备', value: '数值', unit: '单位', total: '总计', current: '当前', target: '目标', mode: '模式', auto: '自动', manual: '手动', all: '全部', active: '活跃', recovered: '已恢复', running: '运行中', paused: '已暂停', idle: '空闲', connected: '已连接', details: '详情', description: '描述', location: '位置', protocol: '协议', version: '版本', date: '日期', period: '周期', size: '大小', records: '记录数', download: '下载', uploadRate: '上传速率' },
  // Dashboard
  dash: { realtimeOverview: '实时监控与控制系统总览', energyTrend24h: '24小时能耗趋势', weeklyComparison: '周能耗对比', systemOverview: '系统状态概览', roomMonitor: '房间环境监控', latestAlarms: '最新报警', viewAll: '查看全部', normalRunning: '正常运行', needProcess: '需处理', currentPower: '当前功率', personnel: '人员在场', elecKw: '电力 (kW)', heatKw: '热能 (kW)', energyKwh: '能耗 (kWh)', exportReport: '导出报表', temp: '温度', humidity: '湿度', person: '人' },
  // Data Acquisition
  dataAcq: { subtitle: '现场设备接入与数据采集管理', totalDevices: '总设备数', dataPoints: '数据点位', onlineProtocols: '在线协议', collectFreq: '采集频率', secPerCycle: '秒/次', trendTitle: '数据点采集趋势（24h）', activePoints: '活跃点位', protocolStatus: '通讯协议状态', deviceList: '现场设备列表', scanNetwork: '扫描网络', addDevice: '添加设备', portLabel: '端口', rateLabel: '速率', deviceCount: '设备数', pointCount: '点位数' },
  // Heating
  heat: { subtitle: '供暖系统监控与控制', supplyTemp: '供水温度', returnTemp: '回水温度', boilerStatus: '锅炉状态', avgValve: '平均阀位', setpoint: '设定值', tempDiff: '温差', loadRate: '负载率', circuitsRunning: '回路运行', trendTitle: '供回水温度趋势（24h）', circuitStatus: '供暖回路状态', circuit: '回路', valvePos: '阀门开度', outdoorTemp: '室外温度', adjustSetpoint: '调整设定值', switchMode: '切换模式' },
  // Ventilation
  vent: { subtitle: '通风系统运行状态与控制', totalSupply: '总送风量', totalExhaust: '总排风量', avgCo2: '平均CO2', filterWarning: '过滤器警告', needReplace: '需更换', trendTitle: '送排风量趋势（24h）', supplyAir: '送风量', exhaustAir: '排风量', ahuStatus: 'AHU机组状态', unit: '机组', filter: '过滤器', changeFilter: '更换过滤器', co2Link: 'CO2联动' },
  // Cooling / PID
  cool: { subtitle: '空调调节与PID控制参数', chilledSupply: '冷水供水', coolingPower: '制冷功率', coolingZones: '制冷区域', cop: 'COP 能效比', returnWater: '回水', totalCapacity: '总装机', pidCurve: 'PID控制响应曲线（实时）', pidParams: '区域PID控制参数', zone: '区域', actualTemp: '实际温度', output: '阀门输出', cooling: '制冷中', standby: '待机', adjustPid: '调整PID参数', proportional: '比例增益', integral: '积分时间', derivative: '微分时间' },
  // Lighting / DALI
  light: { subtitle: 'DALI照明控制与日光联动', daliLights: 'DALI灯具', avgLux: '平均照度', daylightUtil: '日光利用', presenceTrigger: '人感触发', luxTarget: '目标', savingsEffect: '节能效果', today: '今日', luxCurve: '照度曲线（24h）— 日光联动', outdoorLux: '室外照度 (lux)', artificialLux: '人工照明 (lux)', daliGroups: 'DALI 分组状态', scenes: '照明场景', group: '分组', lightCount: '灯具数', brightness: '亮度', illuminance: '照度', on: '开启', off: '关闭', switchScene: '切换场景', adjustBrightness: '调节亮度' },
  // Shading
  shade: { subtitle: '百叶窗/遮阳控制与气象联动', solarRad: '太阳辐射', outdoorBright: '室外亮度', windSpeed: '风速', outdoorTemp: '室外温度', humidityLabel: '湿度', controlPanel: '百叶窗控制面板', position: '位置', bladeAngle: '叶片角度', stuck: '卡滞', allUp: '全部升起', allDown: '全部降下', autoMode: '自动模式' },
  // Schedules
  sched: { subtitle: '时间程序与日历功能管理', activePrograms: '活跃程序', pausedPrograms: '暂停程序', holidays: '节假日', currentMode: '当前模式', configured: '已配置', weekday: '工作日', weekSchedule: '周时间表', programList: '时间程序列表', holidayCalendar: '节假日日历', programName: '程序名称', targetSystem: '目标系统', timeArrange: '时间安排', addProgram: '添加程序', editProgram: '编辑程序', addHoliday: '添加节假日', day: '星期', startTime: '开始', endTime: '结束', closed: '关闭', normal: '正常', energySaving: '节能', holidayMode: '假日模式' },
  // Alarms
  alm: { subtitle: '报警与故障管理 · 分级处理', levelA: 'A级 · 紧急', levelB: 'B级 · 重要', levelC: 'C级 · 提示', acknowledged: '已确认', immediate: '需立即处理', soon: '需尽快处理', planned: '计划处理', responded: '已响应', alarmList: '报警列表', thresholdConfig: '阈值监测配置', param: '参数', lowerLimit: '下限', upperLimit: '上限', alarmLevel: '报警等级', acknowledgeAll: '全部确认', silenceAll: '全部静默', configThreshold: '配置阈值' },
  // Energy
  nrg: { subtitle: '电 · 热 · 水 能耗监测与分析', elecPower: '电力功率', heatPower: '热能功率', waterFlow: '用水量', savingRate: '节能率', dailyAccum: '日累计', vsLastMonth: '较上月', trend24h: '24小时能耗趋势（电/热/水）', monthlyCompare: '月度能耗对比', meterStatus: '计量仪表状态', elec: '电', heat: '热', water: '水', meterId: '表号', meterName: '名称', meterType: '类型', currentVal: '当前值', exportReport: '导出报表', setTarget: '设置目标' },
  // Rooms
  room: { subtitle: '单房间温控 · CO2联动 · 人感控制', totalRooms: '房间总数', occupiedRooms: '有人房间', avgTemp: '平均温度', avgCo2: '平均CO2', allRooms: '所有房间', presence: '人感', tempCtrl: '温控', lightCtrl: '照明', occupied: '有人', vacant: '无人', setpointLabel: '设定', shadingPos: '遮阳', adjustRoom: '调整房间设置', batchConfig: '批量配置' },
  // Trends
  trend: { subtitle: '数据归档与趋势记录分析', trendPoints: '趋势点位', sampleInterval: '采样间隔', archiveData: '归档数据', exportFormat: '导出格式', activePts: '活跃', defaultCycle: '默认周期', past5m: '过去5个月', downloadable: '可下载', trendCurve7d: '趋势曲线（7天）', archiveManage: '数据归档管理', exportCsv: '导出 CSV', dateRange: '选择日期范围', temperature: '温度', humidity: '湿度', co2Label: 'CO2', energy: '能耗', archived: '已归档' },
  // Interfaces
  iface: { subtitle: 'BACnet · KNX · Modbus · DALI 通讯管理', totalProtocols: '协议总数', onlineDevices: '在线设备', offlineIface: '离线接口', dataThroughput: '数据吞吐', configured: '已配置', needFix: '需处理', msgPerSec: '报文/秒', ifaceStatus: '通讯接口状态', eventLog: '通讯事件日志', port: '端口', rate: '速率', restartIface: '重启接口', scanDevices: '扫描设备', info: '信息' },
  // Users
  usr: { subtitle: '用户角色管理 · 权限配置 · 审计日志', totalUsers: '总用户', onlineUsers: '在线用户', roleCount: '角色数', todayOps: '今日操作', registered: '已注册', currentOnline: '当前在线', userList: '用户列表', rolePerms: '角色权限', auditLog: '审计日志', user: '用户', role: '角色', email: '邮箱', lastLogin: '最后登录', permissions: '权限', userCount: '用户数', addUser: '添加用户', editRole: '编辑角色' },
  // Remote
  rmt: { subtitle: '远程访问 · VPN连接 · 软件更新', activeConn: '活跃连接', remoteSessions: '远程会话', pendingUpdates: '待更新', securityStatus: '安全状态', inProgress: '进行中', components: '组件', remoteConn: '远程连接', updateManage: '软件更新管理', connection: '连接', target: '目标', latency: '延迟', component: '组件', currentVer: '当前版本', availableVer: '可用版本', severity: '类型', securityUpdate: '安全更新', recommended: '推荐', latest: '最新', optional: '可选', connectVpn: '连接VPN', disconnectVpn: '断开VPN' },
  // Settings
  set: { subtitle: '系统配置 · 数据备份 · IT安全', sysStatus: '系统状态', database: '数据库', securityLevel: '安全等级', lastBackup: '最近备份', running: '运行', days: '天', todayAuto: '今日自动', sysInfo: '系统信息', dataBackup: '数据备份', backupNow: '立即备份', backupTime: '时间', backupType: '类型', backupSize: '大小', success: '成功', failed: '失败', autoBackup: '自动', manualBackup: '手动', restartService: '重启服务', clearCache: '清除缓存' },
}

const en: typeof zh = {
  dashboard: 'Dashboard',
  welcome: 'Building Management System',
  systemStatus: 'System Status',
  totalAlarms: 'Total Alarms',
  energyConsumption: 'Energy Consumption',
  activeUsers: 'Active Users',
  systemUptime: 'System Uptime',
  nav: {
    dashboard: 'Dashboard', dataAcquisition: 'Data Acquisition', heating: 'Heating Control', ventilation: 'Ventilation',
    cooling: 'AC / PID Control', lighting: 'Lighting / DALI', shading: 'Shading Control', schedules: 'Time Schedules',
    alarms: 'Alarm Management', energy: 'Energy Monitoring', rooms: 'Room Automation', trends: 'Trend Analysis',
    interfaces: 'Interface Mgmt', users: 'User Management', remote: 'Remote Access', settings: 'System Settings',
  },
  status: { normal: 'Normal', warning: 'Warning', alarm: 'Alarm', offline: 'Offline', online: 'Online', maintenance: 'Maintenance' },
  actions: { refresh: 'Refresh', export: 'Export', settings: 'Settings', save: 'Save', cancel: 'Cancel', add: 'Add', edit: 'Edit', delete: 'Delete', confirm: 'Confirm', search: 'Search', reset: 'Reset', close: 'Close', start: 'Start', stop: 'Stop', connect: 'Connect', disconnect: 'Disconnect', backup: 'Backup', update: 'Update', acknowledge: 'Acknowledge', silence: 'Silence' },
  common: { time: 'Time', type: 'Type', name: 'Name', status: 'Status', operation: 'Action', module: 'Module', content: 'Content', level: 'Level', device: 'Device', value: 'Value', unit: 'Unit', total: 'Total', current: 'Current', target: 'Target', mode: 'Mode', auto: 'Auto', manual: 'Manual', all: 'All', active: 'Active', recovered: 'Recovered', running: 'Running', paused: 'Paused', idle: 'Idle', connected: 'Connected', details: 'Details', description: 'Description', location: 'Location', protocol: 'Protocol', version: 'Version', date: 'Date', period: 'Period', size: 'Size', records: 'Records', download: 'Download', uploadRate: 'Upload Rate' },
  dash: { realtimeOverview: 'Real-time monitoring & control overview', energyTrend24h: '24h Energy Trend', weeklyComparison: 'Weekly Comparison', systemOverview: 'System Status Overview', roomMonitor: 'Room Environment', latestAlarms: 'Latest Alarms', viewAll: 'View All', normalRunning: 'Running normally', needProcess: 'Need attention', currentPower: 'Current power', personnel: 'Occupants', elecKw: 'Electricity (kW)', heatKw: 'Heat (kW)', energyKwh: 'Energy (kWh)', exportReport: 'Export Report', temp: 'Temp', humidity: 'Humidity', person: 'ppl' },
  dataAcq: { subtitle: 'Field device integration & data collection', totalDevices: 'Total Devices', dataPoints: 'Data Points', onlineProtocols: 'Online Protocols', collectFreq: 'Collect Frequency', secPerCycle: 'sec/cycle', trendTitle: 'Data Point Collection Trend (24h)', activePoints: 'Active Points', protocolStatus: 'Protocol Status', deviceList: 'Field Device List', scanNetwork: 'Scan Network', addDevice: 'Add Device', portLabel: 'Port', rateLabel: 'Rate', deviceCount: 'Devices', pointCount: 'Points' },
  heat: { subtitle: 'Heating system monitoring & control', supplyTemp: 'Supply Temp', returnTemp: 'Return Temp', boilerStatus: 'Boiler Status', avgValve: 'Avg Valve Position', setpoint: 'Setpoint', tempDiff: 'Temp Diff', loadRate: 'Load Rate', circuitsRunning: 'circuits running', trendTitle: 'Supply/Return Temp Trend (24h)', circuitStatus: 'Heating Circuit Status', circuit: 'Circuit', valvePos: 'Valve Position', outdoorTemp: 'Outdoor Temp', adjustSetpoint: 'Adjust Setpoint', switchMode: 'Switch Mode' },
  vent: { subtitle: 'Ventilation system operation & control', totalSupply: 'Total Supply Air', totalExhaust: 'Total Exhaust Air', avgCo2: 'Avg CO₂', filterWarning: 'Filter Warning', needReplace: 'Need replacement', trendTitle: 'Supply/Exhaust Air Trend (24h)', supplyAir: 'Supply Air', exhaustAir: 'Exhaust Air', ahuStatus: 'AHU Status', unit: 'Unit', filter: 'Filter', changeFilter: 'Change Filter', co2Link: 'CO₂ Linked' },
  cool: { subtitle: 'AC regulation & PID control parameters', chilledSupply: 'Chilled Supply', coolingPower: 'Cooling Power', coolingZones: 'Cooling Zones', cop: 'COP', returnWater: 'Return', totalCapacity: 'Total capacity', pidCurve: 'PID Control Response (Real-time)', pidParams: 'Zone PID Parameters', zone: 'Zone', actualTemp: 'Actual Temp', output: 'Valve Output', cooling: 'Cooling', standby: 'Standby', adjustPid: 'Adjust PID', proportional: 'Proportional', integral: 'Integral', derivative: 'Derivative' },
  light: { subtitle: 'DALI lighting control & daylight linking', daliLights: 'DALI Lights', avgLux: 'Avg Illuminance', daylightUtil: 'Daylight Utilization', presenceTrigger: 'Presence Triggers', luxTarget: 'target', savingsEffect: 'Energy savings', today: 'Today', luxCurve: 'Illuminance Curve (24h) — Daylight Linked', outdoorLux: 'Outdoor Lux', artificialLux: 'Artificial Light (lux)', daliGroups: 'DALI Group Status', scenes: 'Lighting Scenes', group: 'Group', lightCount: 'Lights', brightness: 'Brightness', illuminance: 'Illuminance', on: 'On', off: 'Off', switchScene: 'Switch Scene', adjustBrightness: 'Adjust Brightness' },
  shade: { subtitle: 'Blind/shading control & weather linking', solarRad: 'Solar Radiation', outdoorBright: 'Outdoor Brightness', windSpeed: 'Wind Speed', outdoorTemp: 'Outdoor Temp', humidityLabel: 'Humidity', controlPanel: 'Blind Control Panel', position: 'Position', bladeAngle: 'Blade Angle', stuck: 'Stuck', allUp: 'All Up', allDown: 'All Down', autoMode: 'Auto Mode' },
  sched: { subtitle: 'Time program & calendar management', activePrograms: 'Active Programs', pausedPrograms: 'Paused Programs', holidays: 'Holidays', currentMode: 'Current Mode', configured: 'configured', weekday: 'Weekday', weekSchedule: 'Weekly Schedule', programList: 'Program List', holidayCalendar: 'Holiday Calendar', programName: 'Program', targetSystem: 'Target System', timeArrange: 'Schedule', addProgram: 'Add Program', editProgram: 'Edit Program', addHoliday: 'Add Holiday', day: 'Day', startTime: 'Start', endTime: 'End', closed: 'Closed', normal: 'Normal', energySaving: 'Eco', holidayMode: 'Holiday Mode' },
  alm: { subtitle: 'Alarm & fault management · Priority handling', levelA: 'Level A · Critical', levelB: 'Level B · Major', levelC: 'Level C · Info', acknowledged: 'Acknowledged', immediate: 'Immediate action required', soon: 'Action required soon', planned: 'Planned action', responded: 'Responded', alarmList: 'Alarm List', thresholdConfig: 'Threshold Configuration', param: 'Parameter', lowerLimit: 'Lower Limit', upperLimit: 'Upper Limit', alarmLevel: 'Alarm Level', acknowledgeAll: 'Acknowledge All', silenceAll: 'Silence All', configThreshold: 'Configure Thresholds' },
  nrg: { subtitle: 'Electricity · Heat · Water monitoring & analytics', elecPower: 'Elec Power', heatPower: 'Heat Power', waterFlow: 'Water Flow', savingRate: 'Savings Rate', dailyAccum: 'Daily total', vsLastMonth: 'vs last month', trend24h: '24h Energy Trend (Elec/Heat/Water)', monthlyCompare: 'Monthly Comparison', meterStatus: 'Meter Status', elec: 'Elec', heat: 'Heat', water: 'Water', meterId: 'Meter ID', meterName: 'Name', meterType: 'Type', currentVal: 'Current Value', exportReport: 'Export Report', setTarget: 'Set Target' },
  room: { subtitle: 'Room temp control · CO₂ linked · Presence control', totalRooms: 'Total Rooms', occupiedRooms: 'Occupied Rooms', avgTemp: 'Avg Temperature', avgCo2: 'Avg CO₂', allRooms: 'All rooms', presence: 'Presence', tempCtrl: 'Temp Ctrl', lightCtrl: 'Lighting', occupied: 'Occupied', vacant: 'Vacant', setpointLabel: 'Setpoint', shadingPos: 'Shading', adjustRoom: 'Adjust Room', batchConfig: 'Batch Config' },
  trend: { subtitle: 'Data archiving & trend analysis', trendPoints: 'Trend Points', sampleInterval: 'Sample Interval', archiveData: 'Archive Data', exportFormat: 'Export Format', activePts: 'active', defaultCycle: 'Default cycle', past5m: 'Past 5 months', downloadable: 'Downloadable', trendCurve7d: 'Trend Curve (7 days)', archiveManage: 'Archive Management', exportCsv: 'Export CSV', dateRange: 'Select Date Range', temperature: 'Temperature', humidity: 'Humidity', co2Label: 'CO₂', energy: 'Energy', archived: 'Archived' },
  iface: { subtitle: 'BACnet · KNX · Modbus · DALI communication', totalProtocols: 'Total Protocols', onlineDevices: 'Online Devices', offlineIface: 'Offline Interfaces', dataThroughput: 'Data Throughput', configured: 'configured', needFix: 'need attention', msgPerSec: 'msg/sec', ifaceStatus: 'Interface Status', eventLog: 'Communication Event Log', port: 'Port', rate: 'Rate', restartIface: 'Restart Interface', scanDevices: 'Scan Devices', info: 'Info' },
  usr: { subtitle: 'User role management · Permissions · Audit log', totalUsers: 'Total Users', onlineUsers: 'Online Users', roleCount: 'Roles', todayOps: 'Today Ops', registered: 'registered', currentOnline: 'currently online', userList: 'User List', rolePerms: 'Role Permissions', auditLog: 'Audit Log', user: 'User', role: 'Role', email: 'Email', lastLogin: 'Last Login', permissions: 'Permissions', userCount: 'Users', addUser: 'Add User', editRole: 'Edit Role' },
  rmt: { subtitle: 'Remote access · VPN · Software updates', activeConn: 'Active Connections', remoteSessions: 'Remote Sessions', pendingUpdates: 'Pending Updates', securityStatus: 'Security Status', inProgress: 'in progress', components: 'components', remoteConn: 'Remote Connections', updateManage: 'Software Update Management', connection: 'Connection', target: 'Target', latency: 'Latency', component: 'Component', currentVer: 'Current Version', availableVer: 'Available Version', severity: 'Type', securityUpdate: 'Security Update', recommended: 'Recommended', latest: 'Latest', optional: 'Optional', connectVpn: 'Connect VPN', disconnectVpn: 'Disconnect VPN' },
  set: { subtitle: 'System configuration · Backup · IT security', sysStatus: 'System Status', database: 'Database', securityLevel: 'Security Level', lastBackup: 'Last Backup', running: 'running', days: 'days', todayAuto: 'Today auto', sysInfo: 'System Information', dataBackup: 'Data Backup', backupNow: 'Backup Now', backupTime: 'Time', backupType: 'Type', backupSize: 'Size', success: 'Success', failed: 'Failed', autoBackup: 'Auto', manualBackup: 'Manual', restartService: 'Restart Service', clearCache: 'Clear Cache' },
}

const de: typeof zh = {
  dashboard: 'Übersicht',
  welcome: 'Gebäudemanagementsystem',
  systemStatus: 'Systemstatus',
  totalAlarms: 'Alarme gesamt',
  energyConsumption: 'Energieverbrauch',
  activeUsers: 'Aktive Benutzer',
  systemUptime: 'System-Laufzeit',
  nav: {
    dashboard: 'Übersicht', dataAcquisition: 'Datenerfassung', heating: 'Heizungssteuerung', ventilation: 'Lüftungssteuerung',
    cooling: 'Klimaregelung / PID', lighting: 'Beleuchtung / DALI', shading: 'Sonnenschutz', schedules: 'Zeitprogramme',
    alarms: 'Alarmmanagement', energy: 'Energiemonitoring', rooms: 'Raumautomation', trends: 'Trendanalyse',
    interfaces: 'Schnittstellen', users: 'Benutzerverwaltung', remote: 'Fernwartung', settings: 'Systemeinstellungen',
  },
  status: { normal: 'Normal', warning: 'Warnung', alarm: 'Alarm', offline: 'Offline', online: 'Online', maintenance: 'Wartung' },
  actions: { refresh: 'Aktualisieren', export: 'Exportieren', settings: 'Einstellungen', save: 'Speichern', cancel: 'Abbrechen', add: 'Hinzufügen', edit: 'Bearbeiten', delete: 'Löschen', confirm: 'Bestätigen', search: 'Suchen', reset: 'Zurücksetzen', close: 'Schließen', start: 'Starten', stop: 'Stoppen', connect: 'Verbinden', disconnect: 'Trennen', backup: 'Sicherung', update: 'Aktualisieren', acknowledge: 'Quittieren', silence: 'Stummschalten' },
  common: { time: 'Zeit', type: 'Typ', name: 'Name', status: 'Status', operation: 'Aktion', module: 'Modul', content: 'Inhalt', level: 'Stufe', device: 'Gerät', value: 'Wert', unit: 'Einheit', total: 'Gesamt', current: 'Aktuell', target: 'Ziel', mode: 'Modus', auto: 'Automatisch', manual: 'Manuell', all: 'Alle', active: 'Aktiv', recovered: 'Behoben', running: 'Läuft', paused: 'Pausiert', idle: 'Leerlauf', connected: 'Verbunden', details: 'Details', description: 'Beschreibung', location: 'Standort', protocol: 'Protokoll', version: 'Version', date: 'Datum', period: 'Zeitraum', size: 'Größe', records: 'Einträge', download: 'Herunterladen', uploadRate: 'Upload-Rate' },
  dash: { realtimeOverview: 'Echtzeit-Überwachung & Steuerungsübersicht', energyTrend24h: '24h Energietrend', weeklyComparison: 'Wochenvergleich', systemOverview: 'Systemstatusübersicht', roomMonitor: 'Raumumgebung', latestAlarms: 'Neueste Alarme', viewAll: 'Alle anzeigen', normalRunning: 'Normalbetrieb', needProcess: 'Handlungsbedarf', currentPower: 'Aktuelle Leistung', personnel: 'Anwesende', elecKw: 'Strom (kW)', heatKw: 'Wärme (kW)', energyKwh: 'Energie (kWh)', exportReport: 'Bericht exportieren', temp: 'Temp', humidity: 'Feuchte', person: 'Pers.' },
  dataAcq: { subtitle: 'Feldgeräteanbindung & Datenerfassung', totalDevices: 'Geräte gesamt', dataPoints: 'Datenpunkte', onlineProtocols: 'Online-Protokolle', collectFreq: 'Erfassungsrate', secPerCycle: 'Sek/Zyklus', trendTitle: 'Datenpunkterfassung (24h)', activePoints: 'Aktive Punkte', protocolStatus: 'Protokollstatus', deviceList: 'Feldgeräteliste', scanNetwork: 'Netzwerk scannen', addDevice: 'Gerät hinzufügen', portLabel: 'Port', rateLabel: 'Rate', deviceCount: 'Geräte', pointCount: 'Punkte' },
  heat: { subtitle: 'Heizungssystem Überwachung & Steuerung', supplyTemp: 'Vorlauftemperatur', returnTemp: 'Rücklauftemperatur', boilerStatus: 'Kesselstatus', avgValve: 'Mittl. Ventilstellung', setpoint: 'Sollwert', tempDiff: 'Temp.-Diff.', loadRate: 'Auslastung', circuitsRunning: 'Kreise aktiv', trendTitle: 'Vor-/Rücklauftemperatur (24h)', circuitStatus: 'Heizkreis-Status', circuit: 'Heizkreis', valvePos: 'Ventilstellung', outdoorTemp: 'Außentemperatur', adjustSetpoint: 'Sollwert anpassen', switchMode: 'Modus wechseln' },
  vent: { subtitle: 'Lüftungsanlage Betrieb & Steuerung', totalSupply: 'Gesamtzuluft', totalExhaust: 'Gesamtabluft', avgCo2: 'Mittl. CO₂', filterWarning: 'Filterwarnung', needReplace: 'Wechsel nötig', trendTitle: 'Zu-/Abluft Trend (24h)', supplyAir: 'Zuluft', exhaustAir: 'Abluft', ahuStatus: 'RLT-Gerätestatus', unit: 'Gerät', filter: 'Filter', changeFilter: 'Filter wechseln', co2Link: 'CO₂-geführt' },
  cool: { subtitle: 'Klimaregelung & PID-Parameter', chilledSupply: 'Kaltwasser-VL', coolingPower: 'Kälteleistung', coolingZones: 'Kühlzonen', cop: 'COP', returnWater: 'Rücklauf', totalCapacity: 'Nennleistung', pidCurve: 'PID-Regelverhalten (Echtzeit)', pidParams: 'PID-Parameter je Zone', zone: 'Zone', actualTemp: 'Ist-Temp', output: 'Ventilausgang', cooling: 'Kühlung', standby: 'Bereitschaft', adjustPid: 'PID anpassen', proportional: 'Proportional', integral: 'Integral', derivative: 'Differenzial' },
  light: { subtitle: 'DALI-Beleuchtungssteuerung & Tageslichtregelung', daliLights: 'DALI-Leuchten', avgLux: 'Mittl. Beleuchtungsstärke', daylightUtil: 'Tageslichtnutzung', presenceTrigger: 'Präsenzauslösungen', luxTarget: 'Zielwert', savingsEffect: 'Einspareffekt', today: 'Heute', luxCurve: 'Beleuchtungsstärke (24h) — Tageslichtgeführt', outdoorLux: 'Außen-Lux', artificialLux: 'Kunstlicht (lux)', daliGroups: 'DALI-Gruppenstatus', scenes: 'Lichtszenen', group: 'Gruppe', lightCount: 'Leuchten', brightness: 'Helligkeit', illuminance: 'Beleuchtungsstärke', on: 'Ein', off: 'Aus', switchScene: 'Szene wechseln', adjustBrightness: 'Helligkeit anpassen' },
  shade: { subtitle: 'Jalousie-/Sonnenschutzsteuerung & Wetteranbindung', solarRad: 'Sonnenstrahlung', outdoorBright: 'Außenhelligkeit', windSpeed: 'Windgeschwindigkeit', outdoorTemp: 'Außentemperatur', humidityLabel: 'Feuchte', controlPanel: 'Jalousie-Bedienfeld', position: 'Position', bladeAngle: 'Lamellenwinkel', stuck: 'Blockiert', allUp: 'Alle hoch', allDown: 'Alle runter', autoMode: 'Automatik' },
  sched: { subtitle: 'Zeitprogramme & Kalenderfunktionen', activePrograms: 'Aktive Programme', pausedPrograms: 'Pausierte Programme', holidays: 'Feiertage', currentMode: 'Aktueller Modus', configured: 'konfiguriert', weekday: 'Werktag', weekSchedule: 'Wochenzeitplan', programList: 'Programmliste', holidayCalendar: 'Feiertagskalender', programName: 'Programmname', targetSystem: 'Zielsystem', timeArrange: 'Zeitplan', addProgram: 'Programm hinzufügen', editProgram: 'Programm bearbeiten', addHoliday: 'Feiertag hinzufügen', day: 'Tag', startTime: 'Start', endTime: 'Ende', closed: 'Geschlossen', normal: 'Normal', energySaving: 'Energiesparmodus', holidayMode: 'Feiertagsmodus' },
  alm: { subtitle: 'Alarm- & Störungsmanagement · Priorisierung', levelA: 'Stufe A · Kritisch', levelB: 'Stufe B · Wichtig', levelC: 'Stufe C · Hinweis', acknowledged: 'Quittiert', immediate: 'Sofortiges Handeln erforderlich', soon: 'Baldiges Handeln erforderlich', planned: 'Geplantes Handeln', responded: 'Reagiert', alarmList: 'Alarmliste', thresholdConfig: 'Grenzwertkonfiguration', param: 'Parameter', lowerLimit: 'Untergrenze', upperLimit: 'Obergrenze', alarmLevel: 'Alarmstufe', acknowledgeAll: 'Alle quittieren', silenceAll: 'Alle stummschalten', configThreshold: 'Grenzwerte konfigurieren' },
  nrg: { subtitle: 'Strom · Wärme · Wasser Monitoring & Analyse', elecPower: 'Elektrische Leistung', heatPower: 'Wärmeleistung', waterFlow: 'Wasserverbrauch', savingRate: 'Einsparquote', dailyAccum: 'Tagessumme', vsLastMonth: 'ggü. Vormonat', trend24h: '24h Energietrend (Strom/Wärme/Wasser)', monthlyCompare: 'Monatsvergleich', meterStatus: 'Zählerstatus', elec: 'Strom', heat: 'Wärme', water: 'Wasser', meterId: 'Zähler-ID', meterName: 'Name', meterType: 'Typ', currentVal: 'Aktueller Wert', exportReport: 'Bericht exportieren', setTarget: 'Ziel festlegen' },
  room: { subtitle: 'Einzelraumregelung · CO₂-geführt · Präsenzsteuerung', totalRooms: 'Räume gesamt', occupiedRooms: 'Belegte Räume', avgTemp: 'Mittl. Temperatur', avgCo2: 'Mittl. CO₂', allRooms: 'Alle Räume', presence: 'Präsenz', tempCtrl: 'Temp.-Regelung', lightCtrl: 'Beleuchtung', occupied: 'Belegt', vacant: 'Frei', setpointLabel: 'Sollwert', shadingPos: 'Sonnenschutz', adjustRoom: 'Raum anpassen', batchConfig: 'Stapelkonfiguration' },
  trend: { subtitle: 'Datenarchivierung & Trendanalyse', trendPoints: 'Trendpunkte', sampleInterval: 'Abtastintervall', archiveData: 'Archivdaten', exportFormat: 'Exportformat', activePts: 'aktiv', defaultCycle: 'Standardzyklus', past5m: 'Letzte 5 Monate', downloadable: 'Herunterladbar', trendCurve7d: 'Trendkurve (7 Tage)', archiveManage: 'Archivverwaltung', exportCsv: 'CSV exportieren', dateRange: 'Zeitraum wählen', temperature: 'Temperatur', humidity: 'Feuchte', co2Label: 'CO₂', energy: 'Energie', archived: 'Archiviert' },
  iface: { subtitle: 'BACnet · KNX · Modbus · DALI Kommunikation', totalProtocols: 'Protokolle gesamt', onlineDevices: 'Online-Geräte', offlineIface: 'Offline-Schnittstellen', dataThroughput: 'Datendurchsatz', configured: 'konfiguriert', needFix: 'Handlungsbedarf', msgPerSec: 'Nachr./Sek.', ifaceStatus: 'Schnittstellenstatus', eventLog: 'Kommunikationsereignisse', port: 'Port', rate: 'Rate', restartIface: 'Schnittstelle neu starten', scanDevices: 'Geräte scannen', info: 'Info' },
  usr: { subtitle: 'Benutzerrollen · Berechtigungen · Audit-Log', totalUsers: 'Benutzer gesamt', onlineUsers: 'Online-Benutzer', roleCount: 'Rollen', todayOps: 'Aktionen heute', registered: 'registriert', currentOnline: 'aktuell online', userList: 'Benutzerliste', rolePerms: 'Rollenberechtigungen', auditLog: 'Audit-Log', user: 'Benutzer', role: 'Rolle', email: 'E-Mail', lastLogin: 'Letzte Anmeldung', permissions: 'Berechtigungen', userCount: 'Benutzer', addUser: 'Benutzer hinzufügen', editRole: 'Rolle bearbeiten' },
  rmt: { subtitle: 'Fernzugriff · VPN · Software-Updates', activeConn: 'Aktive Verbindungen', remoteSessions: 'Fernsitzungen', pendingUpdates: 'Ausstehende Updates', securityStatus: 'Sicherheitsstatus', inProgress: 'läuft', components: 'Komponenten', remoteConn: 'Fernverbindungen', updateManage: 'Software-Update-Verwaltung', connection: 'Verbindung', target: 'Ziel', latency: 'Latenz', component: 'Komponente', currentVer: 'Aktuelle Version', availableVer: 'Verfügbare Version', severity: 'Typ', securityUpdate: 'Sicherheitsupdate', recommended: 'Empfohlen', latest: 'Aktuell', optional: 'Optional', connectVpn: 'VPN verbinden', disconnectVpn: 'VPN trennen' },
  set: { subtitle: 'Systemkonfiguration · Datensicherung · IT-Sicherheit', sysStatus: 'Systemstatus', database: 'Datenbank', securityLevel: 'Sicherheitsstufe', lastBackup: 'Letzte Sicherung', running: 'Betrieb', days: 'Tage', todayAuto: 'Heute automatisch', sysInfo: 'Systeminformationen', dataBackup: 'Datensicherung', backupNow: 'Jetzt sichern', backupTime: 'Zeit', backupType: 'Typ', backupSize: 'Größe', success: 'Erfolgreich', failed: 'Fehlgeschlagen', autoBackup: 'Automatisch', manualBackup: 'Manuell', restartService: 'Dienst neu starten', clearCache: 'Cache leeren' },
}

export const translations = { zh, en, de }
